version: '3'
services:
  elasticmq:
    image: softwaremill/elasticmq
    container_name: local-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    environment:
      - DISABLE_UI=false
      - ELASTICMQ_OPTS=-Dconfig.file=/opt/elasticmq.conf
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf:ro


