services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
    restart: always
